name: docker-build

on:
  push:

env:
  EXCALIDRAW_VERSION: master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: excalidraw/excalidraw
          ref: ${{ env.EXCALIDRAW_VERSION }}
          path: excalidraw

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: excalidraw
          platforms: linux/amd64,linux/arm64
          push: true
          tags: stoub/excalidraw:${{ env.EXCALIDRAW_VERSION }}